bind 127.0.0.1
port 6379
protected-mode yes
daemonize yes
dir /Users/arhaan/Desktop/matchvibe/vibemeet-backend/.local-redis
logfile /Users/arhaan/Desktop/matchvibe/vibemeet-backend/.local-redis/redis.log
pidfile /Users/arhaan/Desktop/matchvibe/vibemeet-backend/.local-redis/redis.pid
save ""
appendonly no
