/**
 * Eligibility for profile-related rewards.
 *
 * Signup auto-assigns a default preset avatar (approved) plus username/age/gender,
 * so mere presence of avatar/imageId must NOT unlock photo/complete rewards.
 */

import type { Types } from 'mongoose';
import {
  getDefaultPresetImageId,
  listPresetImageIds,
} from '../images/preset-image-ids';

export type AvatarLike = {
  imageId?: string | null;
  moderationStatus?: string | null;
  uploadedBy?: Types.ObjectId | string | null;
} | null | undefined;

function idStr(v: Types.ObjectId | string | null | undefined): string | null {
  if (v == null) return null;
  return typeof v === 'string' ? v : v.toString();
}

/** All system preset Cloudflare imageIds (default + male/female listings). */
export function collectSystemPresetImageIds(): Set<string> {
  const ids = new Set<string>();
  const def = getDefaultPresetImageId();
  if (def) ids.add(def);
  for (const { imageId } of listPresetImageIds('male')) {
    if (imageId) ids.add(imageId);
  }
  for (const { imageId } of listPresetImageIds('female')) {
    if (imageId) ids.add(imageId);
  }
  return ids;
}

export function isSystemPresetImageId(
  imageId: string | null | undefined
): boolean {
  if (!imageId || !String(imageId).trim()) return false;
  return collectSystemPresetImageIds().has(String(imageId).trim());
}

function isModerationOkForReward(status: string | null | undefined): boolean {
  // Pending/rejected never qualifies. Missing/legacy treated as OK only for
  // non-preset user uploads; presets are already excluded.
  if (status == null || status === '') return true;
  return status === 'approved' || status === 'auto-ok';
}

/**
 * True only when the user has a personal avatar that is not a system preset
 * and passes moderation.
 *
 * - Default signup avatar: preset imageId + uploadedBy null → false
 * - Picking another preset: preset imageId → false
 * - Real upload via commit: unique imageId + uploadedBy user → true (if not pending)
 */
export function hasRewardQualifyingAvatar(
  user: {
    _id?: Types.ObjectId | string;
    avatar?: AvatarLike;
  }
): boolean {
  const avatar = user.avatar;
  if (!avatar?.imageId) return false;
  if (isSystemPresetImageId(avatar.imageId)) return false;
  if (!isModerationOkForReward(avatar.moderationStatus ?? null)) return false;

  // Signup default uses uploadedBy: null. Require a bound uploader.
  const uploader = idStr(avatar.uploadedBy ?? null);
  if (!uploader) return false;

  // Prefer uploader == owner when we know the owner id.
  const owner = idStr(user._id);
  if (owner && uploader !== owner) return false;

  return true;
}

/**
 * Complete-profile reward: user must actively complete profile identity,
 * not the auto-assigned first-login defaults alone.
 */
export function isProfileCompleteForReward(user: {
  _id?: Types.ObjectId | string;
  username?: string | null;
  age?: number | null;
  gender?: string | null;
  avatar?: AvatarLike;
  usernameChangeCount?: number | null;
}): boolean {
  if (!hasRewardQualifyingAvatar(user)) return false;

  const username = typeof user.username === 'string' ? user.username.trim() : '';
  if (username.length < 4) return false;

  // Auto usernames are `u` + random alphanumeric (see buildRandomUsername).
  // Require a real name change or a non-auto-looking handle.
  const looksAutoGenerated = /^u[a-z0-9]{4,9}$/i.test(username);
  const changedUsername = (user.usernameChangeCount ?? 0) >= 1;
  if (looksAutoGenerated && !changedUsername) return false;

  if (typeof user.age !== 'number' || !Number.isFinite(user.age) || user.age < 13) {
    return false;
  }
  if (!user.gender || !String(user.gender).trim()) return false;

  return true;
}
