import { Router } from 'express';
import authRoutes from './modules/auth/auth.routes';
import userRoutes from './modules/user/user.routes';
import creatorRoutes from './modules/creator/creator.routes';
import chatRoutes from './modules/chat/chat.routes';
import videoRoutes from './modules/video/video.routes';
import adminRoutes from './modules/admin/admin.routes';
import billingRoutes from './modules/billing/billing.routes';
import supportRoutes from './modules/support/support.routes';
import paymentRoutes from './modules/payment/payment.routes';
import bdRoutes from './modules/bd/bd.routes';
import agencyRoutes from './modules/agency/agency.routes';
import referralRoutes from './modules/referral/referral.routes';
import appUpdateRoutes from './modules/app-update/app-update.routes';
import availabilityRoutes from './modules/availability/availability.routes';
import imagesRoutes from './modules/images/images.routes';
import metricsRoutes from './modules/metrics/metrics.routes';
import storiesRoutes from './modules/stories/routes/stories.routes';
import momentsRoutes from './modules/moments/routes/moments.routes';
import streamRoutes from './modules/stream/stream.routes';
import vipRoutes from './modules/vip/vip.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/referral', referralRoutes);
router.use('/user', userRoutes);
router.use('/creator', creatorRoutes);
router.use('/chat', chatRoutes);
router.use('/video', videoRoutes);
router.use('/admin', adminRoutes);
router.use('/bd', bdRoutes);
router.use('/agency', agencyRoutes);
router.use('/billing', billingRoutes);
router.use('/support', supportRoutes);
router.use('/payment', paymentRoutes);
router.use('/app-updates', appUpdateRoutes);
router.use('/availability', availabilityRoutes);
router.use('/images', imagesRoutes);
router.use('/metrics', metricsRoutes);
router.use('/stories', storiesRoutes);
router.use('/moments', momentsRoutes);
router.use('/stream', streamRoutes);
router.use('/vip', vipRoutes);

export default router;
